import { useEffect, useMemo, useRef, useState } from 'react'
import { BarChart3, CalendarDays, Camera, Check, Download, FileCheck2, FileText, FolderOpen, LayoutDashboard, Link2, LogOut, Mail, MoreHorizontal, Package, Plus, Search, Settings, Trash2, Upload, Users, Wrench, X } from 'lucide-react'
import { supabase, supabaseConfigured } from './supabase'

type Client={id:string|number;name:string;company:string;email:string;phone?:string;projects:number;value:number;last:string}
type Project={id:string|number;client_id?:string;client:string;title:string;slug:string;type:string;category:string;status:string;published:boolean;cover?:string;description?:string}
type Team={id:string|number;name:string;specialty:string;email:string;phone?:string;active:boolean}
type Shoot={id:string|number;project_id?:string;project:string;title:string;starts_at:string;location:string;status:string;notes?:string}
type Gear={id:string|number;name:string;category:string;serial_number:string;quantity:number;status:string}
type Campaign={id:string|number;name:string;channel:'EMAIL'|'SMS';subject?:string;message:string;status:string;recipient_count:number}
type Invoice={id:string;clientId?:string;client:string;label:string;total:number;due:string;status:'PAYÉE'|'EN ATTENTE'|'EN RETARD'}
type Quote={id:string;clientId?:string;client:string;label:string;total:number;date:string;status:'BROUILLON'|'ENVOYÉ'|'ACCEPTÉ'}
type Media={id:string|number;path?:string;bucket?:string;name:string;src:string;type:'PHOTO'|'VIDÉO';project:string;projectId?:string}
type Analytics={views:number;downloads:number;inquiries:number;galleries:number}
type Drawer='client'|'project'|'team'|'shoot'|'gear'|'campaign'|'quote'|'invoice'|null

const asset=(path:string)=>`${import.meta.env.BASE_URL}${path.replace(/^\//,'')}`
const money=(n:number)=>new Intl.NumberFormat('fr-FR').format(n)+' GNF'
const day=(value:string)=>new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value))
const demoClients:Client[]=[
 {id:1,name:'Aïssatou Diallo',company:'Atelier AD',email:'aissatou@demo.local',projects:3,value:18500000,last:'Aujourd’hui'},
 {id:2,name:'Mamadou Camara',company:'MC Holding',email:'mamadou@demo.local',projects:2,value:12000000,last:'Hier'},
 {id:3,name:'Fatou Bah',company:'Maison FB',email:'fatou@demo.local',projects:1,value:7500000,last:'18 sept.'},
]
const demoProjects:Project[]=[
 {id:1,client:'Atelier AD',title:'Nocturne',slug:'nocturne-demo',type:'PHOTO',category:'ÉDITORIAL',status:'IN_PROGRESS',published:true,cover:asset('media/demo-portrait.jpg')},
 {id:2,client:'MC Holding',title:'Atlantique',slug:'atlantique-demo',type:'FILM',category:'CORPORATE',status:'PLANNED',published:true,cover:asset('media/demo-coast.jpg')},
 {id:3,client:'Maison FB',title:'Matière',slug:'matiere-demo',type:'PHOTO',category:'MODE',status:'DONE',published:true,cover:asset('media/demo-lens.jpg')},
]
const demoTeams:Team[]=[{id:1,name:'Kara Camara',specialty:'Direction photo',email:'kara@grsvision.com',active:true},{id:2,name:'Mariam Condé',specialty:'Production',email:'mariam@demo.local',active:true},{id:3,name:'Alpha Sow',specialty:'Cadreur / monteur',email:'alpha@demo.local',active:true}]
const demoShoots:Shoot[]=[{id:1,project:'Nocturne',title:'Shooting campagne',starts_at:'2026-10-03T09:00',location:'Kaloum',status:'CONFIRMED'},{id:2,project:'Atlantique',title:'Repérage côte',starts_at:'2026-10-07T16:00',location:'Îles de Loos',status:'PLANNED'}]
const demoGear:Gear[]=[{id:1,name:'Sony Alpha 7S III',category:'Caméra',serial_number:'GRS-CAM-001',quantity:2,status:'AVAILABLE'},{id:2,name:'DJI Ronin RS 3 Pro',category:'Stabilisation',serial_number:'GRS-GIM-001',quantity:1,status:'BOOKED'},{id:3,name:'Aputure 600D Pro',category:'Éclairage',serial_number:'GRS-LGT-001',quantity:2,status:'AVAILABLE'}]
const demoInvoices:Invoice[]=[{id:'FAC-2026-018',client:'Atelier AD',label:'Campagne Nocturne',total:12500000,due:'30 sept. 2026',status:'EN ATTENTE'},{id:'FAC-2026-017',client:'MC Holding',label:'Film corporate',total:8000000,due:'20 sept. 2026',status:'EN RETARD'},{id:'FAC-2026-016',client:'Maison FB',label:'Portraits équipe',total:5500000,due:'12 sept. 2026',status:'PAYÉE'}]
const demoQuotes:Quote[]=[{id:'DEV-2026-024',client:'Atelier AD',label:'Collection 2027',total:18000000,date:'25 sept. 2026',status:'ENVOYÉ'},{id:'DEV-2026-023',client:'Maison FB',label:'Pack produit',total:9500000,date:'23 sept. 2026',status:'ACCEPTÉ'}]
const demoMedia:Media[]=[{id:1,name:'nocturne.jpg',src:asset('media/demo-portrait.jpg'),type:'PHOTO',project:'Nocturne'},{id:2,name:'atlantique.jpg',src:asset('media/demo-coast.jpg'),type:'PHOTO',project:'Atlantique'},{id:3,name:'precision.jpg',src:asset('media/demo-lens.jpg'),type:'PHOTO',project:'Matière'}]

export default function AdminWorkspace(){
 const [view,setView]=useState('dashboard'),[notice,setNotice]=useState(''),[loading,setLoading]=useState(supabaseConfigured),[drawer,setDrawer]=useState<Drawer>(null)
 const [clients,setClients]=useState(demoClients),[projects,setProjects]=useState(demoProjects),[teams,setTeams]=useState(demoTeams),[shoots,setShoots]=useState(demoShoots),[gear,setGear]=useState(demoGear),[campaigns,setCampaigns]=useState<Campaign[]>([]),[invoices,setInvoices]=useState(demoInvoices),[quotes,setQuotes]=useState(demoQuotes),[media,setMedia]=useState(demoMedia),[analytics,setAnalytics]=useState<Analytics>({views:0,downloads:0,inquiries:0,galleries:0})
 const [uploadProject,setUploadProject]=useState('');const fileRef=useRef<HTMLInputElement>(null)
 const flash=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(''),2600)}
 const revenue=useMemo(()=>invoices.filter(x=>x.status==='PAYÉE').reduce((s,x)=>s+x.total,0),[invoices]);const outstanding=useMemo(()=>invoices.filter(x=>x.status!=='PAYÉE').reduce((s,x)=>s+x.total,0),[invoices])
 const nav=[['dashboard',LayoutDashboard,'Vue d’ensemble'],['clients',Users,'Clients'],['projects',Camera,'Projets'],['teams',Users,'Équipes'],['shoots',CalendarDays,'Tournages'],['equipment',Package,'Matériel'],['quotes',FileText,'Devis'],['invoices',FileCheck2,'Factures'],['media',FolderOpen,'Médiathèque'],['communication',Mail,'Communication'],['analytics',BarChart3,'Statistiques'],['settings',Settings,'Réglages']] as const
 useEffect(()=>{if(supabase)void loadData()},[])
 const loadData=async()=>{const db=supabase;if(!db)return;setLoading(true);const results=await Promise.all([
  db.from('clients').select('*').order('created_at',{ascending:false}),db.from('projects').select('*,client:clients(name,company)').order('created_at',{ascending:false}),db.from('teams').select('*').order('created_at',{ascending:false}),db.from('shoots').select('*,project:projects(title)').order('starts_at'),db.from('equipment').select('*').order('created_at',{ascending:false}),db.from('communications').select('*').order('created_at',{ascending:false}),db.from('quotes').select('*,client:clients(name)').order('created_at',{ascending:false}),db.from('invoices').select('*,client:clients(name)').order('created_at',{ascending:false}),db.from('media_assets').select('*').order('created_at',{ascending:false}),db.from('analytics_events').select('event_type'),db.from('inquiries').select('id',{count:'exact',head:true}),db.from('client_links').select('id',{count:'exact',head:true}).eq('active',true)
 ]);const [cr,pr,tr,sr,gr,cor,qr,ir,mr,er,inq,links]=results as any[]
 if(cr.error){flash('Migrations Supabase à appliquer');setLoading(false);return}
 const projectRows=pr.data||[];const invoiceRows=ir.data||[]
 setClients((cr.data||[]).map((c:any)=>({id:c.id,name:c.name,company:c.company||'Indépendant',email:c.email||'',phone:c.phone||'',projects:projectRows.filter((p:any)=>p.client_id===c.id).length,value:invoiceRows.filter((i:any)=>i.client_id===c.id).reduce((s:number,i:any)=>s+Number(i.total),0),last:'Récent'})))
 setProjects(projectRows.map((p:any)=>({id:p.id,client_id:p.client_id,client:p.client?.company||p.client?.name||'Interne',title:p.title,slug:p.slug,type:p.project_type,category:p.category||p.project_type,status:p.status,published:p.published,description:p.description})))
 if(!tr.error)setTeams(tr.data||[]);if(!sr.error)setShoots((sr.data||[]).map((s:any)=>({...s,project:s.project?.title||'Sans projet'})));if(!gr.error)setGear(gr.data||[]);if(!cor.error)setCampaigns(cor.data||[])
 setQuotes((qr.data||[]).map((q:any)=>({id:q.number,clientId:q.client_id,client:q.client?.name||'Client',label:q.notes||'Prestation',total:Number(q.total),date:q.issue_date,status:q.status==='ACCEPTED'?'ACCEPTÉ':q.status==='SENT'?'ENVOYÉ':'BROUILLON'})))
 setInvoices(invoiceRows.map((x:any)=>({id:x.number,clientId:x.client_id,client:x.client?.name||'Client',label:x.notes||'Prestation',total:Number(x.total),due:x.due_date||'À définir',status:x.status==='PAID'?'PAYÉE':x.status==='OVERDUE'?'EN RETARD':'EN ATTENTE'})))
 setMedia((mr.data||[]).map((m:any)=>{const {data}=db.storage.from(m.storage_bucket).getPublicUrl(m.storage_path);return{id:m.id,path:m.storage_path,bucket:m.storage_bucket,name:m.storage_path.split('/').pop()||'Média',src:data.publicUrl,type:m.media_type==='VIDEO'?'VIDÉO':'PHOTO',project:'Portfolio'}}))
 const events=er.data||[];setAnalytics({views:events.filter((e:any)=>e.event_type==='PAGE_VIEW').length,downloads:events.filter((e:any)=>e.event_type==='DOWNLOAD').length,inquiries:inq.count||0,galleries:links.count||0});setLoading(false)
 }
 const save=async(type:Exclude<Drawer,null>,form:FormData)=>{const get=(x:string)=>String(form.get(x)||'');let row:any
  if(type==='client')row={name:get('name'),company:get('company'),email:get('email'),phone:get('phone')}
  if(type==='project')row={client_id:get('client')||null,title:get('title'),slug:get('title').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now().toString().slice(-4),project_type:get('type'),description:get('description')||get('category'),status:'DRAFT',visibility:'PUBLIC',published:true,portfolio:true,project_year:new Date().getFullYear()}
  if(type==='team')row={name:get('name'),specialty:get('specialty'),email:get('email'),phone:get('phone'),active:true}
  if(type==='shoot')row={project_id:get('project')||null,title:get('title'),starts_at:get('starts_at'),location:get('location'),status:'PLANNED',notes:get('notes')}
  if(type==='gear')row={name:get('name'),category:get('category'),serial_number:get('serial'),quantity:Number(get('quantity')||1),status:'AVAILABLE'}
  if(type==='campaign')row={name:get('name'),channel:get('channel'),subject:get('subject'),message:get('message'),status:'DRAFT',recipient_count:clients.length}
  if(type==='quote'||type==='invoice'){const clientId=get('client'),c=clients.find(x=>String(x.id)===clientId),total=Number(get('total')),number=`${type==='quote'?'DEV':'FAC'}-${new Date().getFullYear()}-${String((type==='quote'?quotes:invoices).length+1).padStart(3,'0')}`;row={number,client_id:clientId,subtotal:total,total,notes:get('label'),status:type==='quote'?'DRAFT':'SENT'};if(supabase){const {error}=await supabase.from(type==='quote'?'quotes':'invoices').insert(row);if(error){flash('Enregistrement impossible : '+error.message);return}}if(type==='quote')setQuotes(v=>[{id:number,clientId,client:c?.name||'Client',label:get('label'),total,date:'Aujourd’hui',status:'BROUILLON'},...v]);else setInvoices(v=>[{id:number,clientId,client:c?.name||'Client',label:get('label'),total,due:'30 jours',status:'EN ATTENTE'},...v]);setDrawer(null);setView(type==='quote'?'quotes':'invoices');flash(type==='quote'?'Devis créé':'Facture créée');return}
  const table={client:'clients',project:'projects',team:'teams',shoot:'shoots',gear:'equipment',campaign:'communications'}[type];let data:any={id:Date.now(),...row};if(supabase&&table){const result=await supabase.from(table).insert(row).select().single();if(result.error){flash('Enregistrement impossible : '+result.error.message);return}data=result.data}
  if(type==='client')setClients(v=>[{...data,projects:0,value:0,last:'À l’instant'},...v]);if(type==='project')setProjects(v=>[{...data,type:data.project_type,category:get('category'),client:clients.find(c=>String(c.id)===row.client_id)?.company||'Interne'},...v]);if(type==='team')setTeams(v=>[data,...v]);if(type==='shoot')setShoots(v=>[{...data,project:projects.find(p=>String(p.id)===row.project_id)?.title||'Sans projet'},...v]);if(type==='gear')setGear(v=>[data,...v]);if(type==='campaign')setCampaigns(v=>[data,...v]);setDrawer(null);flash('Élément ajouté et synchronisé')
 }
 const upload=async(files:FileList|null)=>{if(!files)return;let count=0;for(const f of [...files]){if(!supabase){setMedia(v=>[{id:Date.now(),name:f.name,src:URL.createObjectURL(f),type:f.type.startsWith('video')?'VIDÉO':'PHOTO',project:'Non classé'},...v]);count++;continue}const path=`${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await supabase.storage.from('portfolio-images').upload(path,f);if(up.error)continue;const inserted=await supabase.from('media_assets').insert({storage_bucket:'portfolio-images',storage_path:path,media_type:f.type.startsWith('video')?'VIDEO':'PHOTO',mime_type:f.type}).select().single();if(inserted.error)continue;if(uploadProject)await supabase.from('project_media').insert({project_id:uploadProject,media_id:inserted.data.id,position:media.length+count,is_featured:media.length===0,visibility:'PUBLIC'});const {data:url}=supabase.storage.from('portfolio-images').getPublicUrl(path);setMedia(v=>[{id:inserted.data.id,path,bucket:'portfolio-images',name:f.name,src:url.publicUrl,type:f.type.startsWith('video')?'VIDÉO':'PHOTO',project:projects.find(p=>String(p.id)===uploadProject)?.title||'Portfolio',projectId:uploadProject},...v]);count++}flash(`${count} média(s) publié(s) dans le portfolio`)}
 const deleteMedia=async(id:string|number)=>{const item=media.find(x=>x.id===id);if(supabase&&item?.path&&item.bucket){await supabase.storage.from(item.bucket).remove([item.path]);await supabase.from('media_assets').delete().eq('id',id)}setMedia(v=>v.filter(x=>x.id!==id));flash('Média supprimé')}
 const markPaid=async(id:string)=>{if(supabase)await supabase.from('invoices').update({status:'PAID',amount_paid:invoices.find(x=>x.id===id)?.total||0}).eq('number',id);setInvoices(v=>v.map(x=>x.id===id?{...x,status:'PAYÉE'}:x));flash('Paiement enregistré')}
 const printInvoice=(x:Invoice)=>{const w=window.open('','_blank','width=900,height=760');if(!w)return;w.document.write(`<!doctype html><html><head><title>${x.id}</title><style>body{font:15px Arial;color:#141414;padding:60px}header{display:flex;justify-content:space-between;border-bottom:1px solid #ddd;padding-bottom:30px}h1{font-size:46px}main{margin:70px 0}.total{font-size:30px;font-weight:bold;text-align:right;border-top:1px solid #ddd;padding-top:30px}small{color:#777}</style></head><body><header><div><b>GRS VISION</b><br><small>Conakry · Guinée</small></div><div><b>FACTURE ${x.id}</b><br><small>Échéance ${x.due}</small></div></header><main><h1>${x.client}</h1><p>${x.label}</p></main><p class="total">TOTAL · ${money(x.total)}</p><small>Document généré depuis GRS Studio Manager.</small><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()}
 const share=async()=>{const url=`${location.origin}${location.pathname.replace(/index\.html$/,'')}#/client/grs-${crypto.randomUUID().slice(0,8)}`;await navigator.clipboard?.writeText(url);flash('Lien client copié')}
 return <div className="studio-admin"><aside className="studio-sidebar"><a className="studio-brand" href="#/"><img src={asset('grs-mark.jpg')}/><span>GRS<small>STUDIO MANAGER</small></span></a><nav>{nav.map(([id,Icon,label])=><button key={id} onClick={()=>setView(id)} className={view===id?'active':''}><Icon/><span>{label}</span></button>)}</nav><div className="storage"><span>STOCKAGE CLOUD</span><b>{media.length} fichiers synchronisés</b><i><em/></i></div><div className="account"><i>K</i><span>Kara<small>Super admin</small></span><MoreHorizontal/></div></aside>
 <main className="studio-main"><header className="studio-top"><div><span className="overline">GRS OPERATIONS · {supabaseConfigured?'LIVE':'DÉMONSTRATION'}</span><h1>{nav.find(n=>n[0]===view)?.[2]}</h1></div><div className="studio-actions"><button className="search"><Search/> Rechercher</button><button className="ghost" onClick={share}><Link2/> Galerie</button><button className="accent" onClick={()=>setDrawer('project')}><Plus/> Nouveau projet</button></div></header>{notice&&<div className="toast"><Check/>{notice}</div>}
 {loading?<section className="panel loading-panel">Synchronisation du studio…</section>:<View view={view} data={{clients,projects,teams,shoots,gear,campaigns,invoices,quotes,media,analytics,revenue,outstanding}} open={setDrawer} setView={setView} share={share} paid={markPaid} print={printInvoice} upload={()=>fileRef.current?.click()} remove={deleteMedia} uploadProject={uploadProject} setUploadProject={setUploadProject}/>}</main>
 <input ref={fileRef} hidden multiple type="file" accept="image/*,video/*" onChange={e=>upload(e.target.files)}/>{drawer&&<Editor type={drawer} clients={clients} projects={projects} close={()=>setDrawer(null)} submit={save}/>}</div>
}

function View({view,data,open,setView,share,paid,print,upload,remove,uploadProject,setUploadProject}:any){const {clients,projects,teams,shoots,gear,campaigns,invoices,quotes,media,analytics,revenue,outstanding}=data
 if(view==='dashboard')return <><section className="welcome"><div><span>PILOTAGE EN TEMPS RÉEL</span><h2>Bonjour Kara.</h2><p>Clients, production et trésorerie réunis dans un seul espace.</p></div><div className="pulse"><i/>{shoots.filter((s:Shoot)=>s.status!=='DONE').length} tournage(s) à venir</div></section><section className="kpis"><Kpi label="ENCAISSÉ" value={money(revenue)} note="Factures payées"/><Kpi label="À ENCAISSER" value={money(outstanding)} note="Relances à suivre"/><Kpi label="PROJETS ACTIFS" value={String(projects.filter((p:Project)=>p.status!=='DONE').length).padStart(2,'0')} note={`${clients.length} clients`}/><Kpi label="PORTFOLIO" value={String(media.length)} note={`${analytics.views} consultations`}/></section><section className="dashboard-columns"><Panel title="Prochains tournages" action="Planning" go={()=>setView('shoots')}>{shoots.slice(0,4).map((s:Shoot)=><Row key={s.id} title={s.title} meta={`${s.project} · ${day(s.starts_at)}`} value={s.location}/>)}</Panel><Panel title="Projets récents" action="Tous les projets" go={()=>setView('projects')}>{projects.slice(0,4).map((p:Project)=><Row key={p.id} title={p.title} meta={`${p.client} · ${p.category}`} value={p.status}/>)}</Panel></section><section className="panel traffic"><PanelHead title="Activité du studio" action="Données en direct"/><div className="traffic-grid"><div><span>VUES DU SITE</span><b>{analytics.views}</b><small>{analytics.downloads} téléchargements</small></div><div className="bars">{[34,51,43,78,62,91,74,55,81,68,88,97].map((h:number,i:number)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="top-project"><img src={projects[0]?.cover||asset('media/demo-portrait.jpg')}/><span>PRODUCTION<b>{shoots.length} sessions</b><small>{gear.filter((g:Gear)=>g.status==='AVAILABLE').length} équipements disponibles</small></span></div></div></section></>
 if(view==='clients')return <TablePage intro={`${clients.length} clients enregistrés`} add="Ajouter un client" onAdd={()=>open('client')}><Table heads={['CLIENT','PROJETS','CA TOTAL','ACTIVITÉ','']}>{clients.map((c:Client)=><div className="table-row" key={c.id}><Person name={c.name} sub={`${c.company} · ${c.email}`}/><span>{c.projects}</span><strong>{money(c.value)}</strong><span>{c.last}</span><button className="dots" onClick={share}><Link2/></button></div>)}</Table></TablePage>
 if(view==='projects')return <TablePage intro={`${projects.length} projets · ${projects.filter((p:Project)=>p.published).length} publiés`} add="Nouveau projet" onAdd={()=>open('project')}><div className="project-admin-grid">{projects.map((p:Project)=><article key={p.id}>{p.cover?<img src={p.cover}/>:<div className="project-placeholder"><Camera/></div>}<span>{p.type} · {p.category}</span><h3>{p.title}</h3><p>{p.client}</p><em>{p.published?'PUBLIC':'PRIVÉ'}</em></article>)}</div></TablePage>
 if(view==='teams')return <TablePage intro="Collaborateurs et rôles de production" add="Ajouter un membre" onAdd={()=>open('team')}><Table heads={['MEMBRE','SPÉCIALITÉ','CONTACT','STATUT','']}>{teams.map((t:Team)=><div className="table-row" key={t.id}><Person name={t.name} sub={t.email}/><b>{t.specialty}</b><span>{t.phone||'—'}</span><em className="pill">ACTIF</em><MoreHorizontal/></div>)}</Table></TablePage>
 if(view==='shoots')return <TablePage intro="Planning des tournages et shootings" add="Planifier" onAdd={()=>open('shoot')}><div className="schedule-grid">{shoots.map((s:Shoot)=><article key={s.id}><time>{day(s.starts_at)}</time><div><span>{s.status}</span><h3>{s.title}</h3><p>{s.project} · {s.location}</p></div></article>)}</div></TablePage>
 if(view==='equipment')return <TablePage intro={`${gear.length} références inventoriées`} add="Ajouter du matériel" onAdd={()=>open('gear')}><Table heads={['MATÉRIEL','CATÉGORIE','IDENTIFIANT','QTÉ / ÉTAT','']}>{gear.map((g:Gear)=><div className="table-row" key={g.id}><Person name={g.name} sub={g.serial_number}/><b>{g.category}</b><span>{g.serial_number}</span><em className="pill">{g.quantity} · {g.status}</em><Wrench/></div>)}</Table></TablePage>
 if(view==='quotes')return <TablePage intro={`${quotes.length} devis · ${money(quotes.reduce((s:number,x:Quote)=>s+x.total,0))}`} add="Créer un devis" onAdd={()=>open('quote')}><Finance rows={quotes}/></TablePage>
 if(view==='invoices')return <TablePage intro={`${money(outstanding)} à encaisser`} add="Créer une facture" onAdd={()=>open('invoice')}><Table heads={['NUMÉRO','CLIENT / OBJET','MONTANT','STATUT','ACTIONS']}>{invoices.map((x:Invoice)=><div className="table-row" key={x.id}><strong>{x.id}</strong><div><b>{x.client}</b><small>{x.label} · {x.due}</small></div><strong>{money(x.total)}</strong><em className="pill">{x.status}</em><div className="row-actions"><button onClick={()=>print(x)} title="Générer le PDF"><Download/></button>{x.status!=='PAYÉE'&&<button onClick={()=>paid(x.id)} title="Marquer payée"><Check/></button>}</div></div>)}</Table></TablePage>
 if(view==='media')return <TablePage intro={`${media.length} médias · publication connectée au site`} add="Charger des médias" onAdd={upload}><div className="media-publish"><label>Associer les prochains fichiers au projet<select value={uploadProject} onChange={e=>setUploadProject(e.target.value)}><option value="">Portfolio général</option>{projects.map((p:Project)=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><small>Les médias associés à un projet public deviennent visibles sur le portfolio.</small></div><div className="media-grid-admin">{media.map((m:Media)=><article key={m.id}><img src={m.src}/><div><span>{m.type}</span><b>{m.name}</b><small>{m.project}</small></div><button onClick={()=>remove(m.id)}><Trash2/></button></article>)}<button className="upload-card" onClick={upload}><Upload/><b>Ajouter images ou vidéos</b><span>Stockage Supabase</span></button></div></TablePage>
 if(view==='communication')return <TablePage intro="Préparez vos campagnes. Les API email et SMS seront branchées ensuite." add="Nouvelle campagne" onAdd={()=>open('campaign')}><div className="campaign-grid">{campaigns.length?campaigns.map((c:Campaign)=><article key={c.id}><span>{c.channel}</span><h3>{c.name}</h3><p>{c.subject||c.message}</p><footer><em>{c.status}</em><b>{c.recipient_count} destinataires</b></footer><button disabled>API À CONNECTER</button></article>):<Empty icon={<Mail/>} title="Aucune campagne" text="Créez un premier brouillon email ou SMS."/>}</div></TablePage>
 if(view==='analytics')return <section className="workspace"><div className="analytics-head">{[['VUES',analytics.views],['GALERIES',analytics.galleries],['TÉLÉCHARGEMENTS',analytics.downloads],['DEMANDES',analytics.inquiries]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>Mesure active</small></div>)}</div><div className="panel chart-panel"><PanelHead title="Consultations" action="Supabase Analytics"/><div className="large-chart">{[20,34,28,52,45,61,58,73,66,82,77,91,86,97,79,88,94,71,83,92,86,99,78,93].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div></section>
 return <section className="workspace settings-clean"><div><span>PROFIL STUDIO</span><h2>Kara · GRS VISION</h2><p>Compte administrateur connecté à Supabase.</p></div><div><span>PUBLICATION</span><h2>GitHub Pages</h2><p>Les mises à jour du code sont déployées automatiquement.</p></div><button className="ghost" onClick={()=>supabase?.auth.signOut()}><LogOut/> Se déconnecter</button></section>
}

function Editor({type,clients,projects,close,submit}:{type:Exclude<Drawer,null>;clients:Client[];projects:Project[];close:()=>void;submit:(t:Exclude<Drawer,null>,f:FormData)=>void}){const title={client:'Nouveau client',project:'Nouveau projet',team:'Nouveau membre',shoot:'Planifier un tournage',gear:'Nouveau matériel',campaign:'Nouvelle campagne',quote:'Nouveau devis',invoice:'Nouvelle facture'}[type];return <div className="drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="drawer"><header><div><span>GRS STUDIO</span><h2>{title}</h2></div><button onClick={close}><X/></button></header><form onSubmit={e=>{e.preventDefault();submit(type,new FormData(e.currentTarget))}}>
 {(type==='client'||type==='team')&&<><Field name="name" label="Nom complet" required/><Field name={type==='client'?'company':'specialty'} label={type==='client'?'Entreprise':'Spécialité'} required/><Field name="email" label="Email" type="email" required/><Field name="phone" label="Téléphone"/></>}
 {type==='project'&&<><Field name="title" label="Titre du projet" required/><Select name="client" label="Client" options={clients.map(c=>[String(c.id),`${c.company} · ${c.name}`])}/><Select name="type" label="Format" options={['PHOTO','FILM'].map(x=>[x,x])}/><Field name="category" label="Catégorie" placeholder="Éditorial, corporate…" required/><Area name="description" label="Description publique"/></>}
 {type==='shoot'&&<><Field name="title" label="Nom du tournage" required/><Select name="project" label="Projet" options={projects.map(p=>[String(p.id),p.title])}/><Field name="starts_at" label="Date et heure" type="datetime-local" required/><Field name="location" label="Lieu" required/><Area name="notes" label="Notes de production"/></>}
 {type==='gear'&&<><Field name="name" label="Matériel" required/><Field name="category" label="Catégorie" required/><Field name="serial" label="Numéro d’inventaire" required/><Field name="quantity" label="Quantité" type="number" required/></>}
 {type==='campaign'&&<><Field name="name" label="Nom de la campagne" required/><Select name="channel" label="Canal" options={['EMAIL','SMS'].map(x=>[x,x])}/><Field name="subject" label="Objet (email)"/><Area name="message" label="Message" required/></>}
 {(type==='quote'||type==='invoice')&&<><Select name="client" label="Client" options={clients.map(c=>[String(c.id),`${c.company} · ${c.name}`])}/><Field name="label" label="Objet / prestation" required/><Field name="total" label="Montant total GNF" type="number" required/></>}
 <button className="accent" type="submit"><Check/> Enregistrer</button></form></aside></div>}

function Field({label,...props}:any){return <label><span>{label}</span><input {...props}/></label>}function Area({label,...props}:any){return <label><span>{label}</span><textarea rows={5} {...props}/></label>}function Select({label,options,...props}:any){return <label><span>{label}</span><select {...props}>{options.map((o:string[])=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label>}
function TablePage({intro,add,onAdd,children}:any){return <section className="workspace"><div className="workspace-toolbar"><p>{intro}</p><button className="accent" onClick={onAdd}><Plus/>{add}</button></div>{children}</section>}
function Table({heads,children}:any){return <div className="data-table"><div className="table-row table-head">{heads.map((h:string)=><span key={h}>{h}</span>)}</div>{children}</div>}
function Person({name,sub}:{name:string;sub:string}){return <div className="person"><i>{name.split(' ').map(x=>x[0]).slice(0,2).join('')}</i><span><b>{name}</b><small>{sub}</small></span></div>}
function Finance({rows}:{rows:Quote[]}){return <Table heads={['NUMÉRO','CLIENT / OBJET','MONTANT','STATUT','']} >{rows.map(q=><div className="table-row" key={q.id}><strong>{q.id}</strong><div><b>{q.client}</b><small>{q.label} · {q.date}</small></div><strong>{money(q.total)}</strong><em className="pill">{q.status}</em><MoreHorizontal/></div>)}</Table>}
function Kpi({label,value,note}:{label:string;value:string;note:string}){return <div className="kpi"><span>{label}</span><b>{value}</b><small>{note}</small></div>}
function PanelHead({title,action}:{title:string;action:string}){return <header className="panel-head"><h3>{title}</h3><button>{action}</button></header>}
function Panel({title,action,go,children}:any){return <div className="panel"><header className="panel-head"><h3>{title}</h3><button onClick={go}>{action}</button></header>{children}</div>}
function Row({title,meta,value}:any){return <div className="line-item"><span className="status"/><div><b>{title}</b><small>{meta}</small></div><em>{value}</em></div>}
function Empty({icon,title,text}:any){return <div className="empty-state">{icon}<h2>{title}</h2><p>{text}</p></div>}
