import { useMemo, useRef, useState } from 'react'
import { BarChart3, BriefcaseBusiness, Check, CircleDollarSign, ClipboardCopy, Download, FileCheck2, FileText, FolderOpen, ImagePlus, LayoutDashboard, Link2, MoreHorizontal, Plus, Search, Send, Settings, Trash2, TrendingUp, Upload, Users, X } from 'lucide-react'

type Client = { id:number; name:string; company:string; email:string; projects:number; value:number; last:string }
type Invoice = { id:string; client:string; label:string; total:number; due:string; status:'PAYÉE'|'EN ATTENTE'|'EN RETARD' }
type Quote = { id:string; client:string; label:string; total:number; date:string; status:'BROUILLON'|'ENVOYÉ'|'ACCEPTÉ' }
type Media = { id:number; name:string; src:string; type:'PHOTO'|'VIDÉO'; project:string }

const asset = (path:string) => `${import.meta.env.BASE_URL}${path.replace(/^\//,'')}`

const seedClients:Client[]=[
  {id:1,name:'Aïssatou Diallo',company:'Atelier AD — DEMO',email:'aissatou@demo.local',projects:3,value:18500000,last:'Aujourd’hui'},
  {id:2,name:'Mamadou Camara',company:'MC Holding — DEMO',email:'mamadou@demo.local',projects:2,value:12000000,last:'Hier'},
  {id:3,name:'Fatou Bah',company:'Maison FB — DEMO',email:'fatou@demo.local',projects:1,value:7500000,last:'18 sept.'},
]
const seedInvoices:Invoice[]=[
  {id:'FAC-2026-018',client:'Atelier AD — DEMO',label:'Campagne Nocturne',total:12500000,due:'30 sept. 2026',status:'EN ATTENTE'},
  {id:'FAC-2026-017',client:'MC Holding — DEMO',label:'Film corporate',total:8000000,due:'20 sept. 2026',status:'EN RETARD'},
  {id:'FAC-2026-016',client:'Maison FB — DEMO',label:'Portraits équipe',total:5500000,due:'12 sept. 2026',status:'PAYÉE'},
]
const seedQuotes:Quote[]=[
  {id:'DEV-2026-024',client:'Atelier AD — DEMO',label:'Couverture collection 2027',total:18000000,date:'25 sept. 2026',status:'ENVOYÉ'},
  {id:'DEV-2026-023',client:'Maison FB — DEMO',label:'Pack produit',total:9500000,date:'23 sept. 2026',status:'ACCEPTÉ'},
  {id:'DEV-2026-022',client:'Nouveau prospect — DEMO',label:'Film événementiel',total:15000000,date:'20 sept. 2026',status:'BROUILLON'},
]
const seedMedia:Media[]=[
  {id:1,name:'nocturne-01.jpg',src:asset('media/demo-portrait.jpg'),type:'PHOTO',project:'Nocturne'},
  {id:2,name:'atlantique-cover.jpg',src:asset('media/demo-coast.jpg'),type:'VIDÉO',project:'Atlantique'},
  {id:3,name:'precision-hero.jpg',src:asset('media/demo-lens.jpg'),type:'PHOTO',project:'Précision'},
]

const money=(n:number)=>new Intl.NumberFormat('fr-FR').format(n)+' GNF'

export default function AdminWorkspace(){
  const [view,setView]=useState('dashboard'); const [clients,setClients]=useState(seedClients); const [invoices,setInvoices]=useState(seedInvoices); const [quotes,setQuotes]=useState(seedQuotes); const [media,setMedia]=useState(seedMedia); const [notice,setNotice]=useState(''); const [drawer,setDrawer]=useState<'client'|'quote'|'invoice'|null>(null); const fileRef=useRef<HTMLInputElement>(null)
  const revenue=useMemo(()=>invoices.filter(x=>x.status==='PAYÉE').reduce((s,x)=>s+x.total,0),[invoices]); const outstanding=useMemo(()=>invoices.filter(x=>x.status!=='PAYÉE').reduce((s,x)=>s+x.total,0),[invoices])
  const flash=(m:string)=>{setNotice(m);window.setTimeout(()=>setNotice(''),2400)}
  const nav=[['dashboard',LayoutDashboard,'Vue d’ensemble'],['clients',Users,'Clients'],['services',BriefcaseBusiness,'Prestations'],['quotes',FileText,'Devis'],['invoices',FileCheck2,'Factures'],['media',FolderOpen,'Médiathèque'],['analytics',BarChart3,'Statistiques'],['settings',Settings,'Réglages']] as const
  const addClient=(form:FormData)=>{setClients(v=>[{id:Date.now(),name:String(form.get('name')),company:String(form.get('company')||'Indépendant'),email:String(form.get('email')),projects:0,value:0,last:'À l’instant'},...v]);setDrawer(null);flash('Client ajouté')}
  const addQuote=(form:FormData)=>{setQuotes(v=>[{id:`DEV-2026-${25+v.length}`,client:String(form.get('client')),label:String(form.get('label')),total:Number(form.get('total')),date:'Aujourd’hui',status:'BROUILLON'},...v]);setDrawer(null);setView('quotes');flash('Devis créé')}
  const addInvoice=(form:FormData)=>{setInvoices(v=>[{id:`FAC-2026-${19+v.length}`,client:String(form.get('client')),label:String(form.get('label')),total:Number(form.get('total')),due:'30 jours',status:'EN ATTENTE'},...v]);setDrawer(null);setView('invoices');flash('Facture créée')}
  const upload=(files:FileList|null)=>{if(!files)return;const added=[...files].map((f,i)=>({id:Date.now()+i,name:f.name,src:URL.createObjectURL(f),type:(f.type.startsWith('video')?'VIDÉO':'PHOTO') as Media['type'],project:'Non classé'}));setMedia(v=>[...added,...v]);flash(`${added.length} média(s) ajouté(s)`)}
  const share=async()=>{const basePath=location.pathname.replace(/index\.html$/,'');const url=`${location.origin}${basePath}#/client/grs-${crypto.randomUUID().slice(0,8)}`;await navigator.clipboard?.writeText(url);flash('Lien client copié')}
  return <div className="studio-admin">
    <aside className="studio-sidebar"><a className="studio-brand" href="#/"><img src={asset('grs-mark.jpg')}/><span>GRS<small>STUDIO MANAGER</small></span></a><nav>{nav.map(([id,Icon,label])=><button key={id} onClick={()=>setView(id)} className={view===id?'active':''}><Icon/><span>{label}</span>{id==='invoices'&&<b>2</b>}</button>)}</nav><div className="storage"><span>STOCKAGE</span><b>18,4 Go / 100 Go</b><i><em/></i></div><div className="account"><i>K</i><span>Kara<small>Super admin</small></span><MoreHorizontal/></div></aside>
    <main className="studio-main"><header className="studio-top"><div><span className="overline">ESPACE PHOTOGRAPHE</span><h1>{nav.find(n=>n[0]===view)?.[2]}</h1></div><div className="studio-actions"><button className="search"><Search/> Rechercher</button><button className="ghost" onClick={share}><Link2/> Partager une galerie</button><button className="accent" onClick={()=>setDrawer('quote')}><Plus/> Nouveau devis</button></div></header>
      {notice&&<div className="toast"><Check/>{notice}</div>}
      {view==='dashboard'&&<Dashboard revenue={revenue} outstanding={outstanding} invoices={invoices} clients={clients} setView={setView}/>} 
      {view==='clients'&&<Clients clients={clients} onAdd={()=>setDrawer('client')} onShare={share}/>} 
      {view==='services'&&<Services/>}
      {view==='quotes'&&<Quotes quotes={quotes} onAdd={()=>setDrawer('quote')} onConvert={(q)=>{setInvoices(v=>[{id:`FAC-2026-${19+v.length}`,client:q.client,label:q.label,total:q.total,due:'30 jours',status:'EN ATTENTE'},...v]);flash('Devis converti en facture')}}/>}
      {view==='invoices'&&<Invoices invoices={invoices} onAdd={()=>setDrawer('invoice')} onPaid={(id)=>{setInvoices(v=>v.map(x=>x.id===id?{...x,status:'PAYÉE'}:x));flash('Paiement enregistré')}}/>}
      {view==='media'&&<MediaLibrary media={media} onUpload={()=>fileRef.current?.click()} onDelete={(id)=>{setMedia(v=>v.filter(x=>x.id!==id));flash('Média supprimé')}}/>}
      {view==='analytics'&&<Analytics/>}
      {view==='settings'&&<SettingsView/>}
    </main>
    <input ref={fileRef} hidden multiple type="file" accept="image/*,video/*" onChange={e=>upload(e.target.files)}/>
    {drawer&&<Drawer type={drawer} clients={clients} close={()=>setDrawer(null)} submit={drawer==='client'?addClient:drawer==='quote'?addQuote:addInvoice}/>} 
  </div>
}

function Dashboard({revenue,outstanding,invoices,clients,setView}:{revenue:number;outstanding:number;invoices:Invoice[];clients:Client[];setView:(v:string)=>void}){return <><section className="welcome"><div><span>JEUDI 25 SEPTEMBRE</span><h2>Bonjour Kara,</h2><p>Voici l’activité de votre studio aujourd’hui.</p></div><div className="pulse"><i/>3 nouvelles interactions client</div></section><section className="kpis"><Kpi label="CHIFFRE D’AFFAIRES ENCAISSÉ" value={money(revenue)} note="+12% ce mois"/><Kpi label="À ENCAISSER" value={money(outstanding)} note="2 factures à suivre"/><Kpi label="GALERIES ACTIVES" value="06" note="142 consultations"/><Kpi label="TÉLÉCHARGEMENTS" value="38" note="Cette semaine"/></section><section className="dashboard-columns"><div className="panel"><PanelHead title="Factures à suivre" action="Toutes les factures" onClick={()=>setView('invoices')}/>{invoices.slice(0,3).map(x=><div className="line-item" key={x.id}><span className={`status ${x.status.toLowerCase().replace(' ','-')}`}/><div><b>{x.client}</b><small>{x.id} · {x.label}</small></div><strong>{money(x.total)}</strong><em>{x.status}</em></div>)}</div><div className="panel"><PanelHead title="Clients récents" action="Tous les clients" onClick={()=>setView('clients')}/>{clients.map(c=><div className="client-mini" key={c.id}><i>{c.name.split(' ').map(x=>x[0]).join('')}</i><div><b>{c.name}</b><small>{c.company}</small></div><span>{c.last}</span></div>)}</div></section><section className="panel traffic"><PanelHead title="Performance du portfolio" action="30 derniers jours"/><div className="traffic-grid"><div><span>VUES DU SITE</span><b>2 847</b><small>+18,2%</small></div><div className="bars">{[34,51,43,78,62,91,74,55,81,68,88,97].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="top-project"><img src={asset('media/demo-portrait.jpg')}/><span>PROJET LE PLUS VU<b>Nocturne</b><small>648 vues · 26 téléchargements</small></span></div></div></section></>}
function Kpi({label,value,note}:{label:string;value:string;note:string}){return <div className="kpi"><span>{label}</span><b>{value}</b><small>{note}</small></div>}
function PanelHead({title,action,onClick}:{title:string;action:string;onClick?:()=>void}){return <header className="panel-head"><h3>{title}</h3><button onClick={onClick}>{action}</button></header>}
function Clients({clients,onAdd,onShare}:{clients:Client[];onAdd:()=>void;onShare:()=>void}){return <section className="workspace"><div className="workspace-toolbar"><label><Search/><input placeholder="Rechercher un client"/></label><button className="ghost" onClick={onShare}><Link2/> Créer un accès client</button><button className="accent" onClick={onAdd}><Plus/> Ajouter un client</button></div><div className="data-table"><div className="table-row table-head"><span>CLIENT</span><span>PROJETS</span><span>CA TOTAL</span><span>DERNIÈRE ACTIVITÉ</span><span/></div>{clients.map(c=><div className="table-row" key={c.id}><div className="person"><i>{c.name[0]}</i><span><b>{c.name}</b><small>{c.company}<br/>{c.email}</small></span></div><span>{c.projects}</span><strong>{money(c.value)}</strong><span>{c.last}</span><button className="dots"><MoreHorizontal/></button></div>)}</div></section>}
function Services(){return <section className="workspace"><div className="workspace-toolbar"><p>Catalogue utilisé dans les devis et demandes du site.</p><button className="accent"><Plus/> Nouvelle prestation</button></div><div className="service-cards">{[['Portrait éditorial','À partir de 4 500 000 GNF','2 h · 15 images'],['Film corporate','Sur devis','Préproduction · tournage · montage'],['Couverture événement','À partir de 6 000 000 GNF','Journée · galerie privée'],['Formation photo','À partir de 1 500 000 GNF','2 jours · 8 participants']].map((s,i)=><article key={s[0]}><span>0{i+1}</span><h3>{s[0]}</h3><p>{s[2]}</p><b>{s[1]}</b><button>Modifier</button></article>)}</div></section>}
function Quotes({quotes,onAdd,onConvert}:{quotes:Quote[];onAdd:()=>void;onConvert:(q:Quote)=>void}){return <section className="workspace"><div className="workspace-toolbar"><p>{quotes.length} devis · {money(quotes.reduce((s,x)=>s+x.total,0))}</p><button className="accent" onClick={onAdd}><Plus/> Créer un devis</button></div><div className="data-table"><div className="table-row quote-row table-head"><span>NUMÉRO</span><span>CLIENT / OBJET</span><span>MONTANT</span><span>STATUT</span><span/></div>{quotes.map(q=><div className="table-row quote-row" key={q.id}><strong>{q.id}</strong><div><b>{q.client}</b><small>{q.label} · {q.date}</small></div><strong>{money(q.total)}</strong><em className={`pill ${q.status.toLowerCase()}`}>{q.status}</em><button className="small-action" onClick={()=>onConvert(q)}>Convertir</button></div>)}</div></section>}
function Invoices({invoices,onAdd,onPaid}:{invoices:Invoice[];onAdd:()=>void;onPaid:(id:string)=>void}){return <section className="workspace"><div className="workspace-toolbar"><p>{money(invoices.filter(x=>x.status!=='PAYÉE').reduce((s,x)=>s+x.total,0))} à encaisser</p><button className="accent" onClick={onAdd}><Plus/> Créer une facture</button></div><div className="data-table"><div className="table-row quote-row table-head"><span>NUMÉRO</span><span>CLIENT / OBJET</span><span>MONTANT</span><span>STATUT</span><span/></div>{invoices.map(x=><div className="table-row quote-row" key={x.id}><strong>{x.id}</strong><div><b>{x.client}</b><small>{x.label} · Échéance {x.due}</small></div><strong>{money(x.total)}</strong><em className={`pill ${x.status.toLowerCase().replace(' ','-')}`}>{x.status}</em>{x.status!=='PAYÉE'?<button className="small-action" onClick={()=>onPaid(x.id)}>Marquer payée</button>:<Check/>}</div>)}</div></section>}
function MediaLibrary({media,onUpload,onDelete}:{media:Media[];onUpload:()=>void;onDelete:(id:number)=>void}){return <section className="workspace"><div className="workspace-toolbar"><p>{media.length} médias · stockage de démonstration</p><button className="accent" onClick={onUpload}><Upload/> Charger des médias</button></div><div className="media-grid-admin">{media.map(m=><article key={m.id}><img src={m.src}/><div><span>{m.type}</span><b>{m.name}</b><small>{m.project}</small></div><button onClick={()=>onDelete(m.id)} aria-label={`Supprimer ${m.name}`}><Trash2/></button></article>)}<button className="upload-card" onClick={onUpload}><ImagePlus/><b>Ajouter des images ou vidéos</b><span>Glissez-déposez ou choisissez des fichiers</span></button></div></section>}
function Analytics(){return <section className="workspace"><div className="analytics-head"><div><span>VUES DU SITE</span><b>2 847</b><small>+18,2%</small></div><div><span>GALERIES CLIENT</span><b>426</b><small>+11,4%</small></div><div><span>TÉLÉCHARGEMENTS</span><b>138</b><small>+24,6%</small></div><div><span>DEMANDES</span><b>17</b><small>+6,2%</small></div></div><div className="panel chart-panel"><PanelHead title="Consultations" action="30 derniers jours"/><div className="large-chart">{[20,34,28,52,45,61,58,73,66,82,77,91,86,97,79,88,94,71,83,92,86,99,78,93].map((h,i)=><i key={i} style={{height:`${h}%`}}/> )}</div></div><div className="dashboard-columns"><div className="panel"><PanelHead title="Pages les plus consultées" action="Vues"/>{[['Accueil','1 024'],['Portfolio','846'],['Nocturne','648'],['Services','329']].map(x=><div className="rank" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><div className="panel"><PanelHead title="Activité client" action="Total"/>{[['Ouvertures de galerie','426'],['Photos téléchargées','138'],['Sélections envoyées','42'],['Projets approuvés','11']].map(x=><div className="rank" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div></section>}
function SettingsView(){return <section className="workspace settings-view"><div className="panel"><PanelHead title="Identité du studio" action="Enregistré"/><label>Nom du studio<input defaultValue="GRS VISION"/></label><label>Email public<input placeholder="À renseigner"/></label><label>Téléphone / WhatsApp<input placeholder="À renseigner"/></label><button className="accent">Enregistrer</button></div><div className="panel"><PanelHead title="Galeries client" action="Sécurité"/><label>Expiration par défaut<select><option>30 jours</option><option>60 jours</option><option>90 jours</option></select></label><label className="toggle-line">Téléchargement par défaut<input type="checkbox"/></label><label className="toggle-line">Watermark de prévisualisation<input type="checkbox" defaultChecked/></label></div></section>}
function Drawer({type,clients,close,submit}:{type:'client'|'quote'|'invoice';clients:Client[];close:()=>void;submit:(f:FormData)=>void}){return <div className="drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="admin-drawer"><header><div><span>NOUVEL ÉLÉMENT</span><h2>{type==='client'?'Ajouter un client':type==='quote'?'Créer un devis':'Créer une facture'}</h2></div><button onClick={close}><X/></button></header><form action={submit}>{type==='client'?<><label>Nom complet<input name="name" required/></label><label>Entreprise<input name="company"/></label><label>Email<input name="email" type="email" required/></label></>:<><label>Client<select name="client" required>{clients.map(c=><option key={c.id}>{c.company}</option>)}</select></label><label>Objet<input name="label" required placeholder="Ex. Couverture événement"/></label><label>Montant (GNF)<input name="total" required type="number" min="0"/></label><label>Notes<textarea rows={5} placeholder="Conditions, livrables, échéance…"/></label></>}<button className="accent" type="submit"><Check/> {type==='client'?'Ajouter le client':type==='quote'?'Créer le devis':'Créer la facture'}</button></form></aside></div>}
